platform :ios, '11.0'

pod 'Flutter', :podspec => 'Flutter/Debug/Flutter.podspec'

target 'CustomTabBarApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomTabBarApp

end
